### ISSUE TITLE
Drain Response.Body

### ISSUE THREAD

**Issue by DmitriyMV** [yanatan16/golang-instagram#3]
Since you're using json.Decoder, I think it would be wise to drain response body for connection reuse. See relevant issue:
https://github.com/google/go-github/pull/317
Discussion:
https://stackoverflow.com/questions/17948827/reusing-http-connections-in-golang
https://groups.google.com/forum/#!search/golang%2420json%2420decode%2420%2420io.Copy/golang-nuts/4Rr8BYVKrAI/ZrJJFTNleekJ 
Solution to this would be something like this

```
defer func() {
    io.CopyN(ioutil.Discard, resp.Body, 512)
    resp.Body.Close()
}()
```

in here https://github.com/yanatan16/golang-instagram/blob/75f0c6a466999127f2b869dd3f47fc479eb9e616/instagram/core.go#L80

If you want I can make a pull request.

Cheers.

**Comment by yanatan16** [comment]
Good idea. I haven't used this project in a while. Would you write a PR please?
